markdown: redcarpet
markdown_ext: markdown,mkd,mkdn,md
highlighter: pygments
permalink: /:year/:month/:title/
safe: false
exclude: ['s3_website.yml']
paginate: 3

# Site settings
title: ZKer
url: "http://sparon.github.io/" # the base hostname & protocol for your site

# 社交账户
username_google: sparon
username_twitter: sparon
username_github: sparon
